In [62]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
import imageio
import os 


## Preprocessing Images

In [220]:
# ## Train Positive
# pos_train_path = "Data/chest_xray/train/PNEUMONIA/"
# train_pos_images = os.listdir(pos_train_path)
# resized_positive_save_path = "resizedImages/train/PNEUMONIA/"
# for x in train_pos_images:
#     img_path = pos_train_path+x
#     img_path = tf.io.read_file(img_path)
#     img = tf.image.decode_jpeg(img_path, channels=3)
#     resized_img = tf.dtypes.cast(tf.image.resize(img, (128,128)), tf.float32)
#     imageio.imwrite(resized_positive_save_path+x, resized_img)
#     print("img {} done".format(x))    

# print("******************** TRAIN POS COMPLETED *********************************")
# ## Train Negative

# neg_train_path = "Data/chest_xray/train/NORMAL/"
# train_neg_images = os.listdir(neg_train_path)
# resized_negative_save_path = "resizedImages/train/NORMAL/"
# for x in train_neg_images:
#     img_path = neg_train_path+x
#     img_path = tf.io.read_file(img_path)
#     img = tf.image.decode_jpeg(img_path, channels=3)
#     resized_img = tf.dtypes.cast(tf.image.resize(img, (128,128)), tf.float32)
#     imageio.imwrite(resized_negative_save_path+x, resized_img)
#     print("img {} done".format(x))    
# print("******************** TRAIN NEG COMPLETED *********************************")

# ## Test Positive
# pos_test_path = "Data/chest_xray/test/PNEUMONIA/"
# test_pos_images = os.listdir(pos_test_path)
# resized_positive_save_path = "resizedImages/test/PNEUMONIA/"
# for x in test_pos_images:
#     img_path = pos_test_path+x
#     img_path = tf.io.read_file(img_path)
#     img = tf.image.decode_jpeg(img_path, channels=3)
#     resized_img = tf.dtypes.cast(tf.image.resize(img, (128,128)), tf.float32)
#     imageio.imwrite(resized_positive_save_path+x, resized_img)
#     print("img {} done".format(x))    

# print("******************** TEST POS COMPLETED *********************************")

# ## Test Negative
# neg_test_path = "Data/chest_xray/test/NORMAL/"
# test_neg_images = os.listdir(neg_test_path)
# resized_negative_save_path = "resizedImages/test/NORMAL/"
# for x in test_neg_images:
#     img_path = neg_test_path+x
#     img_path = tf.io.read_file(img_path)
#     img = tf.image.decode_jpeg(img_path, channels=3)
#     resized_img = tf.dtypes.cast(tf.image.resize(img, (128,128)), tf.float32)
#     imageio.imwrite(resized_negative_save_path+x, resized_img)
#     print("img {} done".format(x))    
# print("******************** TEST NEG COMPLETED *********************************")


        
        

Lossy conversion from float32 to uint8. Range [1.6953125, 252.74609375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 248.2587890625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 222.90045166015625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 214.0859375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 249.17770385742188]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.40234375]. Conv

img IM-0031-0001.jpeg done
img IM-0025-0001.jpeg done
img NORMAL2-IM-0272-0001.jpeg done
img NORMAL2-IM-0102-0001.jpeg done
img NORMAL2-IM-0229-0001.jpeg done
img NORMAL2-IM-0315-0001.jpeg done
img NORMAL2-IM-0123-0001.jpeg done
img NORMAL2-IM-0301-0001.jpeg done
img NORMAL2-IM-0246-0001-0002.jpeg done
img IM-0010-0001.jpeg done
img IM-0046-0001.jpeg done


Lossy conversion from float32 to uint8. Range [0.0, 253.1484375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.25]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.73046875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.1875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [2.7215576171875, 253.333740234375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.70703125]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [2.212890625, 254.8125]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 249.109375]. Co

img NORMAL2-IM-0357-0001.jpeg done
img NORMAL2-IM-0027-0001.jpeg done
img NORMAL2-IM-0033-0001.jpeg done
img NORMAL2-IM-0343-0001.jpeg done
img IM-0028-0001.jpeg done
img NORMAL2-IM-0339-0001.jpeg done
img NORMAL2-IM-0173-0001-0002.jpeg done
img NORMAL2-IM-0012-0001.jpeg done
img NORMAL2-IM-0362-0001.jpeg done
img IM-0009-0001.jpeg done
img NORMAL2-IM-0297-0001.jpeg done
img IM-0073-0001.jpeg done
img IM-0067-0001.jpeg done


Lossy conversion from float32 to uint8. Range [0.0, 254.04443359375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.984375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.9677734375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [1.1953125, 254.890625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.9560546875]. Convert image to uint

img NORMAL2-IM-0283-0001.jpeg done
img NORMAL2-IM-0376-0001.jpeg done
img NORMAL2-IM-0313-0001.jpeg done
img NORMAL2-IM-0019-0001.jpeg done
img NORMAL2-IM-0369-0001.jpeg done
img NORMAL2-IM-0196-0001.jpeg done
img IM-0016-0001.jpeg done
img NORMAL2-IM-0288-0001.jpeg done
img NORMAL2-IM-0241-0001.jpeg done
img IM-0011-0001-0001.jpeg done
img NORMAL2-IM-0131-0001.jpeg done
img NORMAL2-IM-0307-0001.jpeg done
img IM-0037-0001.jpeg done
img NORMAL2-IM-0326-0001.jpeg done


Lossy conversion from float32 to uint8. Range [0.0, 254.86505126953125]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.56161499023438]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.359130859375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.9296875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8

img NORMAL2-IM-0110-0001.jpeg done
img IM-0084-0001.jpeg done
img IM-0059-0001.jpeg done
img NORMAL2-IM-0332-0001.jpeg done
img NORMAL2-IM-0274-0001.jpeg done
img IM-0023-0001.jpeg done
img NORMAL2-IM-0348-0001.jpeg done
img NORMAL2-IM-0381-0001.jpeg done
img IM-0075-0001.jpeg done
img NORMAL2-IM-0364-0001.jpeg done
img NORMAL2-IM-0222-0001.jpeg done
img NORMAL2-IM-0370-0001.jpeg done
img NORMAL2-IM-0146-0001.jpeg done
img IM-0061-0001.jpeg done
img NORMAL2-IM-0285-0001.jpeg done
img NORMAL2-IM-0217-0001.jpeg done


Lossy conversion from float32 to uint8. Range [0.0, 254.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.96923828125]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.2109375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 246.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 248.861572265625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.8515625]. Convert image to uint8 prior to 

img NORMAL2-IM-0351-0001.jpeg done
img IM-0089-0001.jpeg done
img NORMAL2-IM-0092-0001.jpeg done
img NORMAL2-IM-0279-0001.jpeg done
img NORMAL2-IM-0086-0001.jpeg done
img NORMAL2-IM-0345-0001.jpeg done
img NORMAL2-IM-0035-0001.jpeg done
img IM-0097-0001.jpeg done
img NORMAL2-IM-0335-0001.jpeg done
img NORMAL2-IM-0045-0001.jpeg done
img NORMAL2-IM-0273-0001.jpeg done
img NORMAL2-IM-0267-0001.jpeg done
img NORMAL2-IM-0051-0001.jpeg done


Lossy conversion from float32 to uint8. Range [0.0, 251.2314453125]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.975341796875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 252.35284423828125]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.77734375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.76815795898438]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 252.353759765625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.55534

img NORMAL2-IM-0098-0001.jpeg done
img NORMAL2-IM-0321-0001.jpeg done
img NORMAL2-IM-0117-0001.jpeg done
img IM-0083-0001.jpeg done
img IM-0030-0001.jpeg done
img NORMAL2-IM-0246-0001.jpeg done
img NORMAL2-IM-0300-0001.jpeg done
img IM-0011-0001.jpeg done
img IM-0005-0001.jpeg done
img NORMAL2-IM-0252-0001.jpeg done
img IM-0029-0001.jpeg done
img NORMAL2-IM-0081-0001.jpeg done
img NORMAL2-IM-0338-0001.jpeg done


Lossy conversion from float32 to uint8. Range [0.0, 254.765625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.7205352783203]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.736328125]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [4.05078125, 254.34375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.6171875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.17041015625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 250.13998413085938]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 250.5368

img IM-0101-0001.jpeg done
img NORMAL2-IM-0095-0001.jpeg done
img NORMAL2-IM-0210-0001.jpeg done
img NORMAL2-IM-0282-0001.jpeg done
img NORMAL2-IM-0007-0001.jpeg done
img NORMAL2-IM-0141-0001.jpeg done
img NORMAL2-IM-0013-0001.jpeg done
img NORMAL2-IM-0319-0001.jpeg done
img IM-0017-0001.jpeg done
img NORMAL2-IM-0130-0001.jpeg done


Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.8515625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [12.797271728515625, 254.94921875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 252.6541748046875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.89306640625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.986572265625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.38189697

img NORMAL2-IM-0289-0001.jpeg done
img IM-0079-0001.jpeg done
img NORMAL2-IM-0312-0001.jpeg done
img IM-0003-0001.jpeg done
img NORMAL2-IM-0368-0001.jpeg done
img IM-0033-0001-0002.jpeg done
img IM-0091-0001.jpeg done
img NORMAL2-IM-0275-0001.jpeg done
img NORMAL2-IM-0374-0001-0001.jpeg done
img NORMAL2-IM-0105-0001.jpeg done
img NORMAL2-IM-0333-0001.jpeg done
img IM-0022-0001.jpeg done
img NORMAL2-IM-0349-0001.jpeg done


Lossy conversion from float32 to uint8. Range [0.0, 253.49395751953125]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.6875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.00494384765625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 250.56808471679688]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.6875, 253.1875]. Convert image to 

img NORMAL2-IM-0380-0001.jpeg done
img IM-0036-0001.jpeg done
img NORMAL2-IM-0327-0001.jpeg done
img NORMAL2-IM-0111-0001.jpeg done
img IM-0085-0001.jpeg done
img NORMAL2-IM-0237-0001.jpeg done
img NORMAL2-IM-0129-0001.jpeg done
img NORMAL2-IM-0259-0001.jpeg done
img NORMAL2-IM-0290-0001.jpeg done
img NORMAL2-IM-0278-0001.jpeg done
img NORMAL2-IM-0350-0001.jpeg done
img IM-0041-0001.jpeg done
img IM-0107-0001.jpeg done
img IM-0006-0001.jpeg done


Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.8984375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 227.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.09375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.5078125]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.467041015625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 189.63818359375]. Convert image to uint8 prior

img NORMAL2-IM-0251-0001.jpeg done
img NORMAL2-IM-0317-0001.jpeg done
img NORMAL2-IM-0135-0001.jpeg done
img NORMAL2-IM-0303-0001.jpeg done
img NORMAL2-IM-0073-0001.jpeg done
img IM-0049-0001.jpeg done
img NORMAL2-IM-0322-0001.jpeg done
img NORMAL2-IM-0052-0001.jpeg done
img IM-0033-0001.jpeg done
img NORMAL2-IM-0028-0001.jpeg done
img IM-0027-0001.jpeg done
img NORMAL2-IM-0336-0001.jpeg done
img NORMAL2-IM-0360-0001.jpeg done


Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 243.98907470703125]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.7205352783203]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.54177856445312]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.6947021484375]. Convert image t

img IM-0071-0001.jpeg done
img NORMAL2-IM-0281-0001.jpeg done
img IM-0065-0001.jpeg done
img NORMAL2-IM-0374-0001.jpeg done
img NORMAL2-IM-0232-0001.jpeg done
img NORMAL2-IM-0096-0001.jpeg done
img IM-0033-0001-0001.jpeg done
img NORMAL2-IM-0374-0001-0002.jpeg done
img IM-0102-0001.jpeg done
img NORMAL2-IM-0213-0001.jpeg done
img NORMAL2-IM-0207-0001.jpeg done
img NORMAL2-IM-0341-0001.jpeg done
img IM-0050-0001.jpeg done


Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [11.23828125, 254.848388671875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.75604248046875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.09185791015625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 251.715576171875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 251.02734375]. Co

img IM-0099-0001.jpeg done
img IM-0035-0001.jpeg done
img IM-0086-0001.jpeg done
img IM-0109-0001.jpeg done
img NORMAL2-IM-0112-0001.jpeg done
img NORMAL2-IM-0330-0001.jpeg done
img NORMAL2-IM-0276-0001.jpeg done
img IM-0021-0001.jpeg done
img NORMAL2-IM-0311-0001.jpeg done
img NORMAL2-IM-0305-0001.jpeg done
img NORMAL2-IM-0023-0001.jpeg done
img NORMAL2-IM-0353-0001.jpeg done


Lossy conversion from float32 to uint8. Range [0.0, 254.955322265625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 235.77392578125]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.12045288085938]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.9140625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.912841796875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.0379638671875]. Co

img NORMAL2-IM-0329-0001.jpeg done
img NORMAL2-IM-0059-0001.jpeg done
img IM-0110-0001.jpeg done
img NORMAL2-IM-0347-0001.jpeg done
img NORMAL2-IM-0171-0001.jpeg done
img NORMAL2-IM-0201-0001.jpeg done
img IM-0077-0001.jpeg done
img NORMAL2-IM-0150-0001.jpeg done
img NORMAL2-IM-0199-0001.jpeg done
img NORMAL2-IM-0366-0001.jpeg done
img NORMAL2-IM-0372-0001.jpeg done
img IM-0019-0001.jpeg done
img NORMAL2-IM-0287-0001.jpeg done


Lossy conversion from float32 to uint8. Range [0.0, 254.9921875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.547119140625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.65625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.828125]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.109375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 252.227294921875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [11.00714111328125, 254.57421875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 216.528930

img IM-0063-0001.jpeg done
img IM-0069-0001.jpeg done
img NORMAL2-IM-0072-0001.jpeg done
img NORMAL2-IM-0302-0001.jpeg done
img IM-0013-0001.jpeg done
img NORMAL2-IM-0378-0001.jpeg done
img IM-0007-0001.jpeg done
img NORMAL2-IM-0316-0001.jpeg done
img NORMAL2-IM-0120-0001.jpeg done
img NORMAL2-IM-0066-0001.jpeg done
img NORMAL2-IM-0337-0001.jpeg done
img NORMAL2-IM-0271-0001.jpeg done
img IM-0095-0001.jpeg done
img IM-0081-0001.jpeg done


Lossy conversion from float32 to uint8. Range [0.0, 250.998779296875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 232.74343872070312]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 227.078125]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.57891845703125]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.09375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.96658325195312]. Conver

img NORMAL2-IM-0323-0001.jpeg done
img NORMAL2-IM-0359-0001.jpeg done
img NORMAL2-IM-0029-0001.jpeg done
img NORMAL2-IM-0139-0001.jpeg done
img NORMAL2-IM-0249-0001.jpeg done
img NORMAL2-IM-0280-0001.jpeg done
img NORMAL2-IM-0233-0001.jpeg done
img NORMAL2-IM-0361-0001.jpeg done
img IM-0011-0001-0002.jpeg done
img IM-0070-0001.jpeg done
img NORMAL2-IM-0294-0001.jpeg done
img NORMAL2-IM-0340-0001.jpeg done
img NORMAL2-IM-0206-0001.jpeg done


Lossy conversion from float32 to uint8. Range [0.0, 254.43057250976562]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.61505126953125]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.236328125]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.84375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.96868896484375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.27804565429688]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.34033

img NORMAL2-IM-0030-0001.jpeg done
img IM-0103-0001.jpeg done
img IM-0045-0001.jpeg done
img NORMAL2-IM-0354-0001.jpeg done
img NORMAL2-IM-0041-0001.jpeg done
img NORMAL2-IM-0277-0001.jpeg done
img NORMAL2-IM-0107-0001.jpeg done
img NORMAL2-IM-0331-0001.jpeg done
img IM-0093-0001.jpeg done
img NORMAL2-IM-0219-0001.jpeg done
img IM-0087-0001.jpeg done
img NORMAL2-IM-0173-0001-0001.jpeg done
img NORMAL2-IM-0325-0001.jpeg done
img IM-0015-0001.jpeg done


Lossy conversion from float32 to uint8. Range [0.0, 254.96484375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 249.31640625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.328125]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 248.85838317871094]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.74383544921875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [9.121231079101562, 254.9904327392

img NORMAL2-IM-0238-0001.jpeg done
img NORMAL2-IM-0132-0001.jpeg done
img NORMAL2-IM-0304-0001.jpeg done
img NORMAL2-IM-0256-0001.jpeg done
img NORMAL2-IM-0060-0001.jpeg done
img NORMAL2-IM-0310-0001.jpeg done
img NORMAL2-IM-0195-0001.jpeg done
img IM-0001-0001.jpeg done
img IM-0111-0001.jpeg done
img NORMAL2-IM-0346-0001.jpeg done
img NORMAL2-IM-0352-0001.jpeg done
img IM-0039-0001.jpeg done
img NORMAL2-IM-0058-0001.jpeg done
img NORMAL2-IM-0328-0001.jpeg done


Lossy conversion from float32 to uint8. Range [1.720458984375, 244.73779296875]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 253.7734375]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 203.50772094726562]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 232.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.1890869140625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 210.26806640625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 254.9644775390625]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0,

img IM-0043-0001.jpeg done
img IM-0105-0001.jpeg done
img NORMAL2-IM-0373-0001.jpeg done
img NORMAL2-IM-0145-0001.jpeg done
img NORMAL2-IM-0286-0001.jpeg done
img NORMAL2-IM-0079-0001.jpeg done
img NORMAL2-IM-0309-0001.jpeg done
img NORMAL2-IM-0246-0001-0001.jpeg done
img NORMAL2-IM-0292-0001.jpeg done
img NORMAL2-IM-0221-0001.jpeg done
img NORMAL2-IM-0198-0001.jpeg done
******************** TEST NEG COMPLETED *********************************


## Loading, resizing, classifying images

In [290]:
AUTOTUNE = tf.data.experimental.AUTOTUNE
          
def returnLabel(path):
    imgClass = tf.strings.split(path,'/')[-2]
    return 0 if imgClass == 'NORMAL' else 1

def returnImg(path):
    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.convert_image_dtype(img, tf.float32)
    imgClass = returnLabel(path)
    return tf.image.resize(img, (256,256)), imgClass

def getX(image, label):
    return image

def getY(images, label):
    return label


In [291]:
train_path = 'Data/chest_xray/train'
list_ds = tf.data.Dataset.list_files(str(train_path+'/*/*'))
labeled_ds = list_ds.map(returnImg, num_parallel_calls=AUTOTUNE)
labeled_ds

<ParallelMapDataset shapes: ((256, 256, 3), ()), types: (tf.float32, tf.int32)>

In [298]:
X_train = labeled_ds.map(getX)
Y_train = labeled_ds.map(getY)

## Model


In [309]:
for x in X_train.take(10):
    print(x)

tf.Tensor(
[[[0.28440237 0.28440237 0.28440237]
  [0.46291313 0.46291313 0.46291313]
  [0.5491351  0.5491351  0.5491351 ]
  ...
  [0.         0.         0.        ]
  [0.01336278 0.01336278 0.01336278]
  [0.08753829 0.08753829 0.08753829]]

 [[0.26599264 0.26599264 0.26599264]
  [0.3344659  0.3344659  0.3344659 ]
  [0.49562657 0.49562657 0.49562657]
  ...
  [0.         0.         0.        ]
  [0.00997243 0.00997243 0.00997243]
  [0.08541173 0.08541173 0.08541173]]

 [[0.2657311  0.2657311  0.2657311 ]
  [0.27040273 0.27040273 0.27040273]
  [0.41483328 0.41483328 0.41483328]
  ...
  [0.         0.         0.        ]
  [0.01602329 0.01602329 0.01602329]
  [0.08821232 0.08821232 0.08821232]]

 ...

 [[0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  ...
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.         0.         0.        ]
  [0.         0.         0